[aob_patterns.equip_gear]
pattern = "?? 8b f1 ?? 8b d8 ?? 63 ea ?? 8b f9"
offset = "-0x17"

[aob_patterns.equip_goods]
pattern = "?? fa ?? ?? 0f ?? 81 c1 ?? ?? ?? ?? ?? 8b c1 e9"
offset = "0x0"

[aob_patterns.item_give]
pattern = "8B 02 83 F8 0A"
offset = "-0x52"

[cheats]
world_chr_man = "0x3d65f88"
flag_base = "0x19b"
no_goods_base = "0x532"
no_hit_base = "0x530"

[save_backup]
game_man = "0x3d69918"
save_flag_offset = "0xb72"

[cheats.bits]
NoDead = 0
NoDamage = 1
NoFPConsumption = 2
NoStaminaConsumption = 3

[equipment]
game_data_man = "0x3d5df38"
player_game_data = "0x8"
equip_inventory_data = "0x5d0"
magic_slots_base = "0x530"

[equipment.quick_item_offsets]
slot_1 = "0x650"
slot_2 = "0x654"
slot_3 = "0x658"
slot_4 = "0x65C"
slot_5 = "0x660"
slot_6 = "0x664"
slot_7 = "0x668"
slot_8 = "0x66C"
slot_9 = "0x670"
slot_10 = "0x674"

[equipment.magic_slot_offsets]
slot_0 = "0x10"
slot_1 = "0x18"
slot_2 = "0x20"
slot_3 = "0x28"
slot_4 = "0x30"
slot_5 = "0x38"
slot_6 = "0x40"
slot_7 = "0x48"
slot_8 = "0x50"
slot_9 = "0x58"
slot_10 = "0x60"
slot_11 = "0x68"
slot_12 = "0x70"
slot_13 = "0x78"

[item_types]
WEAPON = "0x0"
ARMOR = "0x10000000"
ACCESSORY = "0x20000000"
GOODS = "0x40000000"
OTHER = "0x80000000"
